---
- name: create new directory for nginx location
  file:
    path: /var/www/{{ branch }}
    state: directory
    mode: 0755
    owner: nginx
    group: nginx

- name: put files from repo to new nginx location dir
  copy:
    src: /php/
    dest: /var/www/{{ branch }}
    mode: 0755
    owner: nginx
    group: nginx

- name: create site.conf for new location
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/{{ branch }}.conf
  notify:
    - reload nginx configuration
